let g:signify_vcs_list=['git', 'hg']
"let g:signify_disable_by_default=0
let s:signify_sign='┃'
"let s:signify_sign='│'
"let s:signify_sign='∙'
"let s:signify_sign='❙'
let g:signify_sign_add=s:signify_sign
let g:signify_sign_delete=s:signify_sign
let g:signify_sign_delete_first_line=s:signify_sign
let g:signify_sign_change=s:signify_sign
let g:signify_sign_changedelete=g:signify_sign_change
let g:signify_sign_show_count=0
let g:signify_sign_show_text=1
