" Enable right-click's contextual menu
set mousemodel=popup
"set mousemodel=popup_setpos

" GUI specific font
set guifont=RobotoMono\ Nerd\ Font\ 12

" Line spacing
set linespace=2

" Remove the toolbar
set guioptions-=T

" Remove the right scrollbar
set guioptions-=r
set guioptions-=R

" Remove the left scrollbar
set guioptions-=l
set guioptions-=L

" Remove the menu
set guioptions-=m

" Disable menu tearoff
set guioptions-=t

" Custom tabs label
set guitablabel=%t\ %m

" Enable visual bell
set visualbell

" Easily change font size
command! BiggerFont :let &guifont=substitute(&guifont, '\d\+$', '\=submatch(0)+1', '')
command! SmallerFont :let &guifont=substitute(&guifont, '\d\+$', '\=submatch(0)-1', '')
"nnoremap <silent> <c-scrollwheelup> :BiggerFont<cr>
"inoremap <silent> <c-scrollwheelup> <c-o>:BiggerFont<cr>
"nnoremap <silent> <c-scrollwheeldown> :SmallerFont<cr>
"inoremap <silent> <c-scrollwheeldown> <c-o>:SmallerFont<cr>

" Highlight the current line in insert mode
"augroup HighlightLine
"  autocmd!
"  autocmd InsertEnter * set cursorline
"  autocmd InsertLeave * set nocursorline
"augroup END

" Source a local .gvimrc, if available
if filereadable(expand('~/.vim/gvimrc.local'))
  source ~/.vim/gvimrc.local
endif
